# Copyright (C) 2025  SUSUMU ONUMA
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Flutter Multi-Platform Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          cache: true
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze project
        run: flutter analyze --fatal-infos
      - name: Run tests
        run: flutter test
      - name: Build APK
        run: flutter build apk
      - name: Build App Bundle
        run: flutter build appbundle
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: flutter/build/app/outputs/flutter-apk/
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: android-appbundle
          path: flutter/build/app/outputs/bundle/release/

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    defaults:
      run:
        working-directory: flutter
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          cache: true
      - name: Setup xcconfig for CI
        run: |
          cp ios/Flutter/Release.xcconfig.sample ios/Flutter/Release.xcconfig
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze project
        run: flutter analyze --fatal-infos
      - name: Run tests
        run: flutter test
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      - name: Zip iOS .app
        run: |
          cd build/ios/iphoneos
          ditto -c -k --sequesterRsrc --keepParent Runner.app Runner.zip
      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: flutter/build/ios/iphoneos/Runner.zip

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze project
        run: flutter analyze --fatal-infos
      - name: Run tests
        run: flutter test
      - name: Build Web
        run: flutter build web
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: flutter/build/web

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: flutter
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze project
        run: flutter analyze --fatal-infos
      - name: Run tests
        run: flutter test
      - name: Build Windows
        run: flutter build windows
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: flutter/build/windows/x64/runner/Release/flutter_application.exe

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          cache: true
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze project
        run: flutter analyze --fatal-infos
      - name: Run tests
        run: flutter test
      - name: Build Linux
        run: flutter build linux
      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: flutter/build/linux/x64/release/bundle/flutter_application

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    defaults:
      run:
        working-directory: flutter
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze project
        run: flutter analyze --fatal-infos
      - name: Run tests
        run: flutter test
      - name: Build macOS
        run: flutter build macos
      - name: Zip macOS .app
        run: |
          cd build/macos/Build/Products/Release
          ditto -c -k --sequesterRsrc --keepParent flutter_application.app flutter_application.zip
      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: flutter/build/macos/Build/Products/Release/flutter_application.zip