# Copyright (C) 2025  SUSUMU ONUMA
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
name: Go CI with Dev Container

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  devcontainer-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dev Container CI
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cd pocketbase
            go mod tidy
            go test ./...
            go build -o myapp

      - name: Upload Go App
        uses: actions/upload-artifact@v4
        with:
          name: go-app
          path: pocketbase/myapp

  deploy:
    needs: devcontainer-ci
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: go-app
          path: ./

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          chmod +x myapp
          scp -P ${{ secrets.SSH_PORT || 22 }} myapp ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/opt/pocketbase/
          ssh -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
            if [ ! -d /opt/pocketbase ]; then
              mkdir -p /opt/pocketbase
            fi
            if pgrep -f '/opt/pocketbase/myapp serve' > /dev/null; then
              pkill -f '/opt/pocketbase/myapp serve'
            fi
            mv /opt/pocketbase/myapp /opt/pocketbase/pocketbase
            chmod +x /opt/pocketbase/pocketbase
            nohup /opt/pocketbase/pocketbase serve --dir /opt/pocketbase > /opt/pocketbase/pocketbase.log 2>&1 &
          "

